version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: lebonkoin-db
    restart: always
    environment:
      POSTGRES_DB: lebonkoin
      POSTGRES_USER: lebonkoin_user
      POSTGRES_PASSWORD: lebonkoin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lebonkoin_user -d lebonkoin"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lebonkoin-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://lebonkoin_user:lebonkoin_password@postgres:5432/lebonkoin
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./public:/app/public
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node server.js
      "

  redis:
    image: redis:7-alpine
    container_name: lebonkoin-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
